/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

import javax.swing.JOptionPane;

/**
 *
 * @author juan_
 */
public class JuegoTirarDados extends javax.swing.JFrame {

    private String nombreUsuario;
    private double saldoUsuario;
    
public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}
public void setSaldoUsuario(double saldoUsuario) {
		this.saldoUsuario=saldoUsuario;
                String saldo=String.valueOf(saldoUsuario);
                jLabel14.setText(saldo);
                
	}

    public JuegoTirarDados() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cajaApuesta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan_\\OneDrive\\Documentos\\NetBeansProjects\\casino\\src\\main\\java\\dados\\dado1.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jButton1.setText("Tirar dados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 160, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan_\\OneDrive\\Documentos\\NetBeansProjects\\casino\\src\\main\\java\\dados\\dado2.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan_\\OneDrive\\Documentos\\NetBeansProjects\\casino\\src\\main\\java\\dados\\dado3.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan_\\OneDrive\\Documentos\\NetBeansProjects\\casino\\src\\main\\java\\dados\\dado4.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan_\\OneDrive\\Documentos\\NetBeansProjects\\casino\\src\\main\\java\\dados\\dado5.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan_\\OneDrive\\Documentos\\NetBeansProjects\\casino\\src\\main\\java\\dados\\dado6.png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan_\\OneDrive\\Documentos\\NetBeansProjects\\casino\\src\\main\\java\\dados\\dado1.png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan_\\OneDrive\\Documentos\\NetBeansProjects\\casino\\src\\main\\java\\dados\\dado2.png")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan_\\OneDrive\\Documentos\\NetBeansProjects\\casino\\src\\main\\java\\dados\\dado3.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan_\\OneDrive\\Documentos\\NetBeansProjects\\casino\\src\\main\\java\\dados\\dado4.png")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan_\\OneDrive\\Documentos\\NetBeansProjects\\casino\\src\\main\\java\\dados\\dado5.png")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan_\\OneDrive\\Documentos\\NetBeansProjects\\casino\\src\\main\\java\\dados\\dado6.png")); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel13.setText("Saldo:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(2, 1, 12, 1));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 70, 30));

        jLabel15.setText("Seleccione un numero:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabel16.setText("Ingrese cantidad a apostar:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));
        jPanel1.add(cajaApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            int numeroApostado= (Integer) jSpinner1.getValue();
            String Apuesta= cajaApuesta.getText();
            double cantidadApostada= Double.parseDouble(Apuesta);
            if (cantidadApostada>saldoUsuario){
                JOptionPane.showMessageDialog(null,"Saldo insuficiente");
            } else{
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            jLabel10.setVisible(false);
            jLabel11.setVisible(false);
            jLabel12.setVisible(false);
            int dado1 = (int)(Math.random()*6)+1;
            int dado2 = (int)(Math.random()*6)+1;
            if (dado1==1){
                jLabel1.setVisible(true);
            } if (dado1==2){
                jLabel2.setVisible(true);
            } if (dado1==3){
                jLabel3.setVisible(true);
            } if (dado1==4){
                jLabel4.setVisible(true);
            } if (dado1==5){
                jLabel5.setVisible(true);
            } if (dado1==6){
                jLabel6.setVisible(true);
            }
            if (dado2==1){
                jLabel7.setVisible(true);
            } if (dado2==2){
                jLabel8.setVisible(true);
            } if (dado2==3){
                jLabel9.setVisible(true);
            } if (dado2==4){
                jLabel10.setVisible(true);
            } if (dado2==5){
                jLabel11.setVisible(true);
            } if (dado2==6){
                jLabel12.setVisible(true);
            }
            int resultado= dado1+dado2;
            if(resultado==numeroApostado){
                cantidadApostada= 10*cantidadApostada;
                saldoUsuario= saldoUsuario+cantidadApostada;
                JOptionPane.showMessageDialog(null, "El resultado es: "+resultado+"\n"+
                        "Has ganado: "+cantidadApostada);
                String saldo = String.valueOf(saldoUsuario);
                jLabel14.setText(saldo);
            } else {
                cantidadApostada= -1*cantidadApostada;
                saldoUsuario= saldoUsuario+cantidadApostada;
                JOptionPane.showMessageDialog(null, "El resultado es: "+resultado+"\n"+
                        "Has perdido: "+cantidadApostada);
                String saldo = String.valueOf(saldoUsuario);
                jLabel14.setText(saldo);
            }
            }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VentanaListaJuegos listaJuegos= new VentanaListaJuegos();
        listaJuegos.setSaldoUsuario(saldoUsuario);
        listaJuegos.setNombreUsuario(nombreUsuario);
        listaJuegos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoTirarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoTirarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoTirarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoTirarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoTirarDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cajaApuesta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
